const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, '../src/i18n/locales');
if (!fs.existsSync(localesDir)) fs.mkdirSync(localesDir, { recursive: true });

const it = {
  nav: { fridge: "Frigo", recipes: "Chef AI", scanner: "Scanner", profile: "Profilo" },
  dashboard: { title: "Il Mio Frigo", empty: "Il tuo frigo è vuoto!", add_item: "Aggiungi", scan_barcode: "Scansiona Codice", search: "Cerca prodotto...", expiring_soon: "In Scadenza" },
  profile: { title: "Profilo", biometric: "Sicurezza Biometrica", biometric_desc: "Usa l'impronta digitale o il Face ID per accedere più rapidamente e in totale sicurezza.", notifications: "Notifiche Scadenza", family: "Frigo di Famiglia", family_pro: "PRO IN ARRIVO", preferences: "Le mie Preferenze", support: "Aiuto e Supporto", settings: "Impostazioni App", language: "Lingua / Language", logout: "Esci dall'Account", pro_badge: "UTENTE PRO" },
  stats: { title: "Soldi Risparmiati", saved: "Salvati", wasted: "Sprecati", desc_saved: "valore dei cibi consumati", desc_wasted: "valore dei cibi buttati" }
};

const translations = {
  'en': { nav: { fridge: "Fridge", recipes: "Chef AI", scanner: "Scanner", profile: "Profile" }, dashboard: { title: "My Fridge", empty: "Your fridge is empty!", add_item: "Add", scan_barcode: "Scan Barcode", search: "Search product...", expiring_soon: "Expiring Soon" }, profile: { title: "Profile", biometric: "Biometric Security", biometric_desc: "Use fingerprint or Face ID to login faster and securely.", notifications: "Expiration Alerts", family: "Family Fridge", family_pro: "PRO COMING SOON", preferences: "My Preferences", support: "Help & Support", settings: "App Settings", language: "Lingua / Language", logout: "Log Out", pro_badge: "PRO USER" }, stats: { title: "Money Saved", saved: "Saved", wasted: "Wasted", desc_saved: "value of consumed food", desc_wasted: "value of wasted food" } },
  'fr': { nav: { fridge: "Frigo", recipes: "Chef IA", scanner: "Scanner", profile: "Profil" }, dashboard: { title: "Mon Frigo", empty: "Votre frigo est vide !", add_item: "Ajouter", scan_barcode: "Scanner Code", search: "Chercher produit...", expiring_soon: "Expire Bientôt" }, profile: { title: "Profil", biometric: "Sécurité Biométrique", biometric_desc: "Utilisez l'empreinte ou Face ID pour vous connecter.", notifications: "Alertes d'Expiration", family: "Frigo Familial", family_pro: "PRO BIENTÔT", preferences: "Mes Préférences", support: "Aide & Support", settings: "Paramètres de l'App", language: "Lingua / Language", logout: "Se Déconnecter", pro_badge: "UTILISATEUR PRO" }, stats: { title: "Argent Économisé", saved: "Économisé", wasted: "Gaspillé", desc_saved: "valeur des aliments consommés", desc_wasted: "valeur des aliments gaspillés" } },
  'es': { nav: { fridge: "Nevera", recipes: "Chef IA", scanner: "Escáner", profile: "Perfil" }, dashboard: { title: "Mi Nevera", empty: "¡Tu nevera está vacía!", add_item: "Añadir", scan_barcode: "Escanear Código", search: "Buscar producto...", expiring_soon: "Caduca Pronto" }, profile: { title: "Perfil", biometric: "Seguridad Biométrica", biometric_desc: "Usa huella dactilar o Face ID para iniciar sesión.", notifications: "Alertas de Caducidad", family: "Nevera Familiar", family_pro: "PRO PRÓXIMAMENTE", preferences: "Mis Preferencias", support: "Ayuda y Soporte", settings: "Ajustes de la App", language: "Lingua / Language", logout: "Cerrar Sesión", pro_badge: "USUARIO PRO" }, stats: { title: "Dinero Ahorrado", saved: "Ahorrado", wasted: "Desperdiciado", desc_saved: "valor de comida consumida", desc_wasted: "valor de comida tirada" } },
  'de': { nav: { fridge: "Kühlschrank", recipes: "Chef KI", scanner: "Scanner", profile: "Profil" }, dashboard: { title: "Mein Kühlschrank", empty: "Dein Kühlschrank ist leer!", add_item: "Hinzufügen", scan_barcode: "Barcode scannen", search: "Produkt suchen...", expiring_soon: "Läuft bald ab" }, profile: { title: "Profil", biometric: "Biometrische Sicherheit", biometric_desc: "Verwende Fingerabdruck oder Face ID.", notifications: "Ablaufwarnungen", family: "Familien-Kühlschrank", family_pro: "PRO BALD VERFÜGBAR", preferences: "Meine Einstellungen", support: "Hilfe & Support", settings: "App-Einstellungen", language: "Lingua / Language", logout: "Abmelden", pro_badge: "PRO-NUTZER" }, stats: { title: "Geld gespart", saved: "Gespart", wasted: "Verschwendet", desc_saved: "Wert der verbrauchten Lebensmittel", desc_wasted: "Wert der verschwendeten Lebensmittel" } },
  'zh': { nav: { fridge: "冰箱", recipes: "AI大厨", scanner: "扫描仪", profile: "个人资料" }, dashboard: { title: "我的冰箱", empty: "您的冰箱是空的！", add_item: "添加", scan_barcode: "扫描条形码", search: "搜索产品...", expiring_soon: "即将过期" }, profile: { title: "个人资料", biometric: "生物识别安全", biometric_desc: "使用指纹或面容ID登录。", notifications: "过期提醒", family: "家庭冰箱", family_pro: "PRO即将推出", preferences: "我的偏好", support: "帮助与支持", settings: "应用设置", language: "Lingua / Language", logout: "登出", pro_badge: "高级用户" }, stats: { title: "节省的金额", saved: "已节省", wasted: "已浪费", desc_saved: "消耗食物的价值", desc_wasted: "浪费食物的价值" } },
  'ja': { nav: { fridge: "冷蔵庫", recipes: "AIシェフ", scanner: "スキャナー", profile: "プロフィール" }, dashboard: { title: "私の冷蔵庫", empty: "冷蔵庫は空です！", add_item: "追加", scan_barcode: "バーコードをスキャン", search: "製品を検索...", expiring_soon: "もうすぐ期限切れ" }, profile: { title: "プロフィール", biometric: "生体認証セキュリティ", biometric_desc: "指紋またはFace IDを使用します。", notifications: "期限切れ警告", family: "家族の冷蔵庫", family_pro: "まもなくPRO", preferences: "設定", support: "ヘルプとサポート", settings: "アプリ設定", language: "Lingua / Language", logout: "ログアウト", pro_badge: "PROユーザー" }, stats: { title: "節約したお金", saved: "節約", wasted: "無駄", desc_saved: "消費された食べ物の価値", desc_wasted: "無駄になった食べ物の価値" } },
  'ar': { nav: { fridge: "ثلاجة", recipes: "شيف ذكاء اصطناعي", scanner: "ماسح", profile: "حساب تعريفي" }, dashboard: { title: "ثلاجتي", empty: "ثلاجتك فارغة!", add_item: "إضافة", scan_barcode: "مسح الرمز", search: "البحث عن منتج...", expiring_soon: "تنتهي صلاحيته قريباً" }, profile: { title: "حساب تعريفي", biometric: "الأمان البيومتري", biometric_desc: "استخدم البصمة أو معرف الوجه لتسجيل الدخول.", notifications: "تنبيهات انتهاء الصلاحية", family: "ثلاجة العائلة", family_pro: "PRO قريباً", preferences: "تفضيلاتي", support: "المساعدة والدعم", settings: "إعدادات التطبيق", language: "Lingua / Language", logout: "تسجيل الخروج", pro_badge: "مستخدم PRO" }, stats: { title: "المال المدخر", saved: "تم توفيره", wasted: "ضائع", desc_saved: "قيمة الطعام المستهلك", desc_wasted: "قيمة الطعام المهدر" } },
  'ka': { nav: { fridge: "მაცივარი", recipes: "AI შეფი", scanner: "სკანერი", profile: "პროფილი" }, dashboard: { title: "ჩემი მაცივარი", empty: "შენი მაცივარი ცარიელია!", add_item: "დამატება", scan_barcode: "შტრიხკოდის სკანირება", search: "პროდუქტის ძებნა...", expiring_soon: "მალე ვადა გასდის" }, profile: { title: "პროფილი", biometric: "ბიომეტრიული უსაფრთხოება", biometric_desc: "გამოიყენეთ თითის ანაბეჭდი.", notifications: "ვადის გასვლის შეტყობინებები", family: "ოჯახის მაცივარი", family_pro: "PRO მალე", preferences: "ჩემი პარამეტრები", support: "დახმარება და მხარდაჭერა", settings: "აპლიკაციის პარამეტრები", language: "Lingua / Language", logout: "გასვლა", pro_badge: "PRO მომხმარებელი" }, stats: { title: "დაზოგილი ფული", saved: "დაზოგილია", wasted: "დაკარგული", desc_saved: "მოხმარებული საკვების ღირებულება", desc_wasted: "დაკარგული საკვების ღირებულება" } },
  'hi': { nav: { fridge: "फ्रिज", recipes: "एआई शेफ", scanner: "स्कैनर", profile: "प्रोफ़ाइल" }, dashboard: { title: "मेरा फ्रिज", empty: "आपका फ्रिज खाली है!", add_item: "जोड़ें", scan_barcode: "बारकोड स्कैन करें", search: "उत्पाद खोजें...", expiring_soon: "जल्द ही समाप्त" }, profile: { title: "प्रोफ़ाइल", biometric: "बायोमेट्रिक सुरक्षा", biometric_desc: "लॉग इन करने के लिए फिंगरप्रिंट का उपयोग करें।", notifications: "समाप्ति अलर्ट", family: "परिवार का फ्रिज", family_pro: "जल्द आ रहा है", preferences: "मेरी प्राथमिकताएँ", support: "मदद और समर्थन", settings: "ऐप सेटिंग", language: "Lingua / Language", logout: "लॉग आउट", pro_badge: "प्रो उपयोगकर्ता" }, stats: { title: "पैसे बचाए गए", saved: "बचाया", wasted: "बर्बाद", desc_saved: "खपत किए गए भोजन का मूल्य", desc_wasted: "बर्बाद भोजन का मूल्य" } }
};

for (const [lang, obj] of Object.entries(translations)) {
  fs.writeFileSync(path.join(localesDir, `${lang}.json`), JSON.stringify(obj, null, 2));
}
fs.writeFileSync(path.join(localesDir, 'it.json'), JSON.stringify(it, null, 2));

console.log("Locales generated!");
